///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace setupMyrian_complexFlow
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SetupMyrian recording.
    /// </summary>
    [TestModule("79f0650c-6dc5-4dc5-a3ea-6428cbe7544d", ModuleType.Recording, 1)]
    public partial class SetupMyrian : ITestModule
    {
        /// <summary>
        /// Holds an instance of the setupMyrian_complexFlowRepository repository.
        /// </summary>
        public static setupMyrian_complexFlowRepository repo = setupMyrian_complexFlowRepository.Instance;

        static SetupMyrian instance = new SetupMyrian();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SetupMyrian()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SetupMyrian Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='False') on item 'MyrianR2010Intrasense.CheckBox410'.", repo.MyrianR2010Intrasense.CheckBox410Info, new RecordItemIndex(0));
            Validate.Attribute(repo.MyrianR2010Intrasense.CheckBox410Info, "Checked", "False");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MyrianR2010Intrasense.ComboBox400'.", repo.MyrianR2010Intrasense.ComboBox400Info, new RecordItemIndex(1));
            Validate.Exists(repo.MyrianR2010Intrasense.ComboBox400Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Démarrer l'installation') on item 'MyrianR2010Intrasense.Button1'.", repo.MyrianR2010Intrasense.Button1Info, new RecordItemIndex(2));
            Validate.Attribute(repo.MyrianR2010Intrasense.Button1Info, "Text", "Démarrer l'installation");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (ControlId='2') on item 'MyrianR2010Intrasense.Button2'.", repo.MyrianR2010Intrasense.Button2Info, new RecordItemIndex(3));
            Validate.Attribute(repo.MyrianR2010Intrasense.Button2Info, "ControlId", "2");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianR2010Intrasense.Button1' at 43;16.", repo.MyrianR2010Intrasense.Button1Info, new RecordItemIndex(4));
            repo.MyrianR2010Intrasense.Button1.Click("43;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='WixUI_Bmp_Dialog') on item 'InstallationDeMyrian.Text322'.", repo.InstallationDeMyrian.Text322Info, new RecordItemIndex(5));
            Validate.Attribute(repo.InstallationDeMyrian.Text322Info, "Text", "WixUI_Bmp_Dialog");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (ControlId='374') on item 'InstallationDeMyrian.Button374'.", repo.InstallationDeMyrian.Button374Info, new RecordItemIndex(6));
            Validate.Attribute(repo.InstallationDeMyrian.Button374Info, "ControlId", "374");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (ControlId='311') on item 'InstallationDeMyrian.Button311'.", repo.InstallationDeMyrian.Button311Info, new RecordItemIndex(7));
            Validate.Attribute(repo.InstallationDeMyrian.Button311Info, "ControlId", "311");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InstallationDeMyrian.Button311' at 47;11.", repo.InstallationDeMyrian.Button311Info, new RecordItemIndex(8));
            repo.InstallationDeMyrian.Button311.Click("47;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (ControlId='380') on item 'InstallationDeMyrian.Button380'.", repo.InstallationDeMyrian.Button380Info, new RecordItemIndex(9));
            Validate.Attribute(repo.InstallationDeMyrian.Button380Info, "ControlId", "380");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (ControlId='379') on item 'InstallationDeMyrian.Button379'.", repo.InstallationDeMyrian.Button379Info, new RecordItemIndex(10));
            Validate.Attribute(repo.InstallationDeMyrian.Button379Info, "ControlId", "379");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InstallationDeMyrian.Button379' at 36;10.", repo.InstallationDeMyrian.Button379Info, new RecordItemIndex(11));
            repo.InstallationDeMyrian.Button379.Click("36;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='WixUI_Bmp_Dialog') on item 'InstallationDeMyrian.Text322'.", repo.InstallationDeMyrian.Text322Info, new RecordItemIndex(12));
            Validate.Attribute(repo.InstallationDeMyrian.Text322Info, "Text", "WixUI_Bmp_Dialog");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InstallationDeMyrian.Button374' at 29;9.", repo.InstallationDeMyrian.Button374Info, new RecordItemIndex(13));
            repo.InstallationDeMyrian.Button374.Click("29;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (ControlId='441') on item 'InstallationDeMyrian.Text441'.", repo.InstallationDeMyrian.Text441Info, new RecordItemIndex(14));
            Validate.Attribute(repo.InstallationDeMyrian.Text441Info, "ControlId", "441");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='&Modifier...') on item 'InstallationDeMyrian.Button445'.", repo.InstallationDeMyrian.Button445Info, new RecordItemIndex(15));
            Validate.Attribute(repo.InstallationDeMyrian.Button445Info, "Text", "&Modifier...");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='&Précédent') on item 'InstallationDeMyrian.Button352'.", repo.InstallationDeMyrian.Button352Info, new RecordItemIndex(16));
            Validate.Attribute(repo.InstallationDeMyrian.Button352Info, "Text", "&Précédent");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='&Suivant') on item 'InstallationDeMyrian.Button374'.", repo.InstallationDeMyrian.Button374Info, new RecordItemIndex(17));
            Validate.Attribute(repo.InstallationDeMyrian.Button374Info, "Text", "&Suivant");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Annuler') on item 'InstallationDeMyrian.Button311'.", repo.InstallationDeMyrian.Button311Info, new RecordItemIndex(18));
            Validate.Attribute(repo.InstallationDeMyrian.Button311Info, "Text", "Annuler");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InstallationDeMyrian.Button352' at 28;12.", repo.InstallationDeMyrian.Button352Info, new RecordItemIndex(19));
            repo.InstallationDeMyrian.Button352.Click("28;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='WixUI_Bmp_Dialog') on item 'InstallationDeMyrian.Text322'.", repo.InstallationDeMyrian.Text322Info, new RecordItemIndex(20));
            Validate.Attribute(repo.InstallationDeMyrian.Text322Info, "Text", "WixUI_Bmp_Dialog");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InstallationDeMyrian.Button374' at 21;15.", repo.InstallationDeMyrian.Button374Info, new RecordItemIndex(21));
            repo.InstallationDeMyrian.Button374.Click("21;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='C:\\Program Files\\Intrasense\\Myrian\\') on item 'InstallationDeMyrian.Text441'.", repo.InstallationDeMyrian.Text441Info, new RecordItemIndex(22));
            Validate.Attribute(repo.InstallationDeMyrian.Text441Info, "Text", "C:\\Program Files\\Intrasense\\Myrian\\");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InstallationDeMyrian.Button311' at 19;10.", repo.InstallationDeMyrian.Button311Info, new RecordItemIndex(23));
            repo.InstallationDeMyrian.Button311.Click("19;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (ControlId='380') on item 'InstallationDeMyrian.Button380'.", repo.InstallationDeMyrian.Button380Info, new RecordItemIndex(24));
            Validate.Attribute(repo.InstallationDeMyrian.Button380Info, "ControlId", "380");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (ControlId='379') on item 'InstallationDeMyrian.Button379'.", repo.InstallationDeMyrian.Button379Info, new RecordItemIndex(25));
            Validate.Attribute(repo.InstallationDeMyrian.Button379Info, "ControlId", "379");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InstallationDeMyrian.Button379' at 31;10.", repo.InstallationDeMyrian.Button379Info, new RecordItemIndex(26));
            repo.InstallationDeMyrian.Button379.Click("31;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='&Modifier...') on item 'InstallationDeMyrian.Button445'.", repo.InstallationDeMyrian.Button445Info, new RecordItemIndex(27));
            Validate.Attribute(repo.InstallationDeMyrian.Button445Info, "Text", "&Modifier...");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InstallationDeMyrian.Button374' at 51;9.", repo.InstallationDeMyrian.Button374Info, new RecordItemIndex(28));
            repo.InstallationDeMyrian.Button374.Click("51;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='&Précédent') on item 'InstallationDeMyrian.Button352'.", repo.InstallationDeMyrian.Button352Info, new RecordItemIndex(29));
            Validate.Attribute(repo.InstallationDeMyrian.Button352Info, "Text", "&Précédent");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='&Installer') on item 'InstallationDeMyrian.Button408'.", repo.InstallationDeMyrian.Button408Info, new RecordItemIndex(30));
            Validate.Attribute(repo.InstallationDeMyrian.Button408Info, "Text", "&Installer");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Annuler') on item 'InstallationDeMyrian.Button311'.", repo.InstallationDeMyrian.Button311Info, new RecordItemIndex(31));
            Validate.Attribute(repo.InstallationDeMyrian.Button311Info, "Text", "Annuler");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Cliquez sur Installer pour commencer l'installation. Cliquez sur Précédent pour vérifier ou modifier vos paramètres d'installation. Cliquez sur Annuler pour quitter l'Assistant.') on item 'InstallationDeMyrian.Text460'.", repo.InstallationDeMyrian.Text460Info, new RecordItemIndex(32));
            Validate.Attribute(repo.InstallationDeMyrian.Text460Info, "Text", "Cliquez sur Installer pour commencer l'installation. Cliquez sur Précédent pour vérifier ou modifier vos paramètres d'installation. Cliquez sur Annuler pour quitter l'Assistant.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InstallationDeMyrian.Button352' at 37;9.", repo.InstallationDeMyrian.Button352Info, new RecordItemIndex(33));
            repo.InstallationDeMyrian.Button352.Click("37;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='C:\\Program Files\\Intrasense\\Myrian\\') on item 'InstallationDeMyrian.Text441'.", repo.InstallationDeMyrian.Text441Info, new RecordItemIndex(34));
            Validate.Attribute(repo.InstallationDeMyrian.Text441Info, "Text", "C:\\Program Files\\Intrasense\\Myrian\\");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InstallationDeMyrian.Button374' at 26;11.", repo.InstallationDeMyrian.Button374Info, new RecordItemIndex(35));
            repo.InstallationDeMyrian.Button374.Click("26;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Cliquez sur Installer pour commencer l'installation. Cliquez sur Précédent pour vérifier ou modifier vos paramètres d'installation. Cliquez sur Annuler pour quitter l'Assistant.') on item 'InstallationDeMyrian.Text460'.", repo.InstallationDeMyrian.Text460Info, new RecordItemIndex(36));
            Validate.Attribute(repo.InstallationDeMyrian.Text460Info, "Text", "Cliquez sur Installer pour commencer l'installation. Cliquez sur Précédent pour vérifier ou modifier vos paramètres d'installation. Cliquez sur Annuler pour quitter l'Assistant.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InstallationDeMyrian.Button311' at 43;13.", repo.InstallationDeMyrian.Button311Info, new RecordItemIndex(37));
            repo.InstallationDeMyrian.Button311.Click("43;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (ControlId='380') on item 'InstallationDeMyrian.Button380'.", repo.InstallationDeMyrian.Button380Info, new RecordItemIndex(38));
            Validate.Attribute(repo.InstallationDeMyrian.Button380Info, "ControlId", "380");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (ControlId='379') on item 'InstallationDeMyrian.Button379'.", repo.InstallationDeMyrian.Button379Info, new RecordItemIndex(39));
            Validate.Attribute(repo.InstallationDeMyrian.Button379Info, "ControlId", "379");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InstallationDeMyrian.Button379' at 50;14.", repo.InstallationDeMyrian.Button379Info, new RecordItemIndex(40));
            repo.InstallationDeMyrian.Button379.Click("50;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Cliquez sur Installer pour commencer l'installation. Cliquez sur Précédent pour vérifier ou modifier vos paramètres d'installation. Cliquez sur Annuler pour quitter l'Assistant.') on item 'InstallationDeMyrian.Text460'.", repo.InstallationDeMyrian.Text460Info, new RecordItemIndex(41));
            Validate.Attribute(repo.InstallationDeMyrian.Text460Info, "Text", "Cliquez sur Installer pour commencer l'installation. Cliquez sur Précédent pour vérifier ou modifier vos paramètres d'installation. Cliquez sur Annuler pour quitter l'Assistant.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InstallationDeMyrian.Button408' at 55;11.", repo.InstallationDeMyrian.Button408Info, new RecordItemIndex(42));
            repo.InstallationDeMyrian.Button408.Click("55;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Veuillez patienter pendant que l'Assistant Installation installe Myrian.') on item 'InstallationDeMyrian.Text383'.", repo.InstallationDeMyrian.Text383Info, new RecordItemIndex(43));
            Validate.Attribute(repo.InstallationDeMyrian.Text383Info, "Text", "Veuillez patienter pendant que l'Assistant Installation installe Myrian.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='') on item 'MyrianRConfigurationC2005Intrasens.Text1004'.", repo.MyrianRConfigurationC2005Intrasens.Text1004Info, new RecordItemIndex(44));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Text1004Info, "Text", "");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='') on item 'MyrianRConfigurationC2005Intrasens.Text1005'.", repo.MyrianRConfigurationC2005Intrasens.Text1005Info, new RecordItemIndex(45));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Text1005Info, "Text", "");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='') on item 'MyrianRConfigurationC2005Intrasens.Text1006'.", repo.MyrianRConfigurationC2005Intrasens.Text1006Info, new RecordItemIndex(46));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Text1006Info, "Text", "");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='') on item 'MyrianRConfigurationC2005Intrasens.Text1007'.", repo.MyrianRConfigurationC2005Intrasens.Text1007Info, new RecordItemIndex(47));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Text1007Info, "Text", "");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='') on item 'MyrianRConfigurationC2005Intrasens.Text1008'.", repo.MyrianRConfigurationC2005Intrasens.Text1008Info, new RecordItemIndex(48));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Text1008Info, "Text", "");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='') on item 'MyrianRConfigurationC2005Intrasens.Text1009'.", repo.MyrianRConfigurationC2005Intrasens.Text1009Info, new RecordItemIndex(49));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Text1009Info, "Text", "");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Coller') on item 'MyrianRConfigurationC2005Intrasens.Button1016'.", repo.MyrianRConfigurationC2005Intrasens.Button1016Info, new RecordItemIndex(50));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Button1016Info, "Text", "Coller");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Annuler') on item 'MyrianRConfigurationC2005Intrasens.Button2'.", repo.MyrianRConfigurationC2005Intrasens.Button2Info, new RecordItemIndex(51));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Button2Info, "Text", "Annuler");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='&Suivant >') on item 'MyrianRConfigurationC2005Intrasens.Button1'.", repo.MyrianRConfigurationC2005Intrasens.Button1Info, new RecordItemIndex(52));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Button1Info, "Text", "&Suivant >");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfigurationC2005Intrasens.Button2' at 18;8.", repo.MyrianRConfigurationC2005Intrasens.Button2Info, new RecordItemIndex(53));
            repo.MyrianRConfigurationC2005Intrasens.Button2.Click("18;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (ControlId='6') on item 'MyrianRConfiguration.Button6'.", repo.MyrianRConfiguration.Button6Info, new RecordItemIndex(54));
            Validate.Attribute(repo.MyrianRConfiguration.Button6Info, "ControlId", "6");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (ControlId='7') on item 'MyrianRConfiguration.Button7'.", repo.MyrianRConfiguration.Button7Info, new RecordItemIndex(55));
            Validate.Attribute(repo.MyrianRConfiguration.Button7Info, "ControlId", "7");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfiguration.Button7' at 44;17.", repo.MyrianRConfiguration.Button7Info, new RecordItemIndex(56));
            repo.MyrianRConfiguration.Button7.Click("44;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfigurationC2005Intrasens.Text1004' at 30;13.", repo.MyrianRConfigurationC2005Intrasens.Text1004Info, new RecordItemIndex(57));
            repo.MyrianRConfigurationC2005Intrasens.Text1004.Click("30;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Capital}CIBS' with focus on 'MyrianRConfigurationC2005Intrasens.Text1004'.", repo.MyrianRConfigurationC2005Intrasens.Text1004Info, new RecordItemIndex(58));
            repo.MyrianRConfigurationC2005Intrasens.Text1004.PressKeys("{Capital}CIBS");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfigurationC2005Intrasens.Text1005' at 18;11.", repo.MyrianRConfigurationC2005Intrasens.Text1005Info, new RecordItemIndex(59));
            repo.MyrianRConfigurationC2005Intrasens.Text1005.Click("18;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'PNE{NumPad4}' with focus on 'MyrianRConfigurationC2005Intrasens.Text1005'.", repo.MyrianRConfigurationC2005Intrasens.Text1005Info, new RecordItemIndex(60));
            repo.MyrianRConfigurationC2005Intrasens.Text1005.PressKeys("PNE{NumPad4}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfigurationC2005Intrasens.Text1006' at 12;10.", repo.MyrianRConfigurationC2005Intrasens.Text1006Info, new RecordItemIndex(61));
            repo.MyrianRConfigurationC2005Intrasens.Text1006.Click("12;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'LCQC' with focus on 'MyrianRConfigurationC2005Intrasens.Text1006'.", repo.MyrianRConfigurationC2005Intrasens.Text1006Info, new RecordItemIndex(62));
            repo.MyrianRConfigurationC2005Intrasens.Text1006.PressKeys("LCQC");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfigurationC2005Intrasens.Text1007' at 11;11.", repo.MyrianRConfigurationC2005Intrasens.Text1007Info, new RecordItemIndex(63));
            repo.MyrianRConfigurationC2005Intrasens.Text1007.Click("11;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ACMN' with focus on 'MyrianRConfigurationC2005Intrasens.Text1007'.", repo.MyrianRConfigurationC2005Intrasens.Text1007Info, new RecordItemIndex(64));
            repo.MyrianRConfigurationC2005Intrasens.Text1007.PressKeys("ACMN");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfigurationC2005Intrasens.Text1008' at 19;12.", repo.MyrianRConfigurationC2005Intrasens.Text1008Info, new RecordItemIndex(65));
            repo.MyrianRConfigurationC2005Intrasens.Text1008.Click("19;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'GEIM' with focus on 'MyrianRConfigurationC2005Intrasens.Text1008'.", repo.MyrianRConfigurationC2005Intrasens.Text1008Info, new RecordItemIndex(66));
            repo.MyrianRConfigurationC2005Intrasens.Text1008.PressKeys("GEIM");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfigurationC2005Intrasens.Text1009' at 32;13.", repo.MyrianRConfigurationC2005Intrasens.Text1009Info, new RecordItemIndex(67));
            repo.MyrianRConfigurationC2005Intrasens.Text1009.Click("32;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad6}P{NumPad3}M' with focus on 'MyrianRConfigurationC2005Intrasens.Text1009'.", repo.MyrianRConfigurationC2005Intrasens.Text1009Info, new RecordItemIndex(68));
            repo.MyrianRConfigurationC2005Intrasens.Text1009.PressKeys("{NumPad6}P{NumPad3}M");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfigurationC2005Intrasens.Button1' at 32;14.", repo.MyrianRConfigurationC2005Intrasens.Button1Info, new RecordItemIndex(69));
            repo.MyrianRConfigurationC2005Intrasens.Button1.Click("32;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MyrianRConfigurationC2005Intrasens.RadioButton1010'.", repo.MyrianRConfigurationC2005Intrasens.RadioButton1010Info, new RecordItemIndex(70));
            Validate.Exists(repo.MyrianRConfigurationC2005Intrasens.RadioButton1010Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MyrianRConfigurationC2005Intrasens.RadioButton1011'.", repo.MyrianRConfigurationC2005Intrasens.RadioButton1011Info, new RecordItemIndex(71));
            Validate.Exists(repo.MyrianRConfigurationC2005Intrasens.RadioButton1011Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Annuler') on item 'MyrianRConfigurationC2005Intrasens.Button2'.", repo.MyrianRConfigurationC2005Intrasens.Button2Info, new RecordItemIndex(72));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Button2Info, "Text", "Annuler");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='< &Précédent') on item 'MyrianRConfigurationC2005Intrasens.Button1003'.", repo.MyrianRConfigurationC2005Intrasens.Button1003Info, new RecordItemIndex(73));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Button1003Info, "Text", "< &Précédent");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='&Suivant >') on item 'MyrianRConfigurationC2005Intrasens.Button1'.", repo.MyrianRConfigurationC2005Intrasens.Button1Info, new RecordItemIndex(74));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Button1Info, "Text", "&Suivant >");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfigurationC2005Intrasens.Button2' at 65;13.", repo.MyrianRConfigurationC2005Intrasens.Button2Info, new RecordItemIndex(75));
            repo.MyrianRConfigurationC2005Intrasens.Button2.Click("65;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (ControlId='6') on item 'MyrianRConfiguration.Button6'.", repo.MyrianRConfiguration.Button6Info, new RecordItemIndex(76));
            Validate.Attribute(repo.MyrianRConfiguration.Button6Info, "ControlId", "6");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (ControlId='7') on item 'MyrianRConfiguration.Button7'.", repo.MyrianRConfiguration.Button7Info, new RecordItemIndex(77));
            Validate.Attribute(repo.MyrianRConfiguration.Button7Info, "ControlId", "7");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfiguration.Button7' at 32;16.", repo.MyrianRConfiguration.Button7Info, new RecordItemIndex(78));
            repo.MyrianRConfiguration.Button7.Click("32;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MyrianRConfigurationC2005Intrasens.RadioButton1011'.", repo.MyrianRConfigurationC2005Intrasens.RadioButton1011Info, new RecordItemIndex(79));
            Validate.Exists(repo.MyrianRConfigurationC2005Intrasens.RadioButton1011Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfigurationC2005Intrasens.RadioButton1011' at 8;9.", repo.MyrianRConfigurationC2005Intrasens.RadioButton1011Info, new RecordItemIndex(80));
            repo.MyrianRConfigurationC2005Intrasens.RadioButton1011.Click("8;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfigurationC2005Intrasens.Button1003' at 34;14.", repo.MyrianRConfigurationC2005Intrasens.Button1003Info, new RecordItemIndex(81));
            repo.MyrianRConfigurationC2005Intrasens.Button1003.Click("34;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='CIBS') on item 'MyrianRConfigurationC2005Intrasens.Text1004'.", repo.MyrianRConfigurationC2005Intrasens.Text1004Info, new RecordItemIndex(82));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Text1004Info, "Text", "CIBS");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfigurationC2005Intrasens.Button1' at 41;11.", repo.MyrianRConfigurationC2005Intrasens.Button1Info, new RecordItemIndex(83));
            repo.MyrianRConfigurationC2005Intrasens.Button1.Click("41;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MyrianRConfigurationC2005Intrasens.RadioButton1011'.", repo.MyrianRConfigurationC2005Intrasens.RadioButton1011Info, new RecordItemIndex(84));
            Validate.Exists(repo.MyrianRConfigurationC2005Intrasens.RadioButton1011Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfigurationC2005Intrasens.RadioButton1010' at 7;8.", repo.MyrianRConfigurationC2005Intrasens.RadioButton1010Info, new RecordItemIndex(85));
            repo.MyrianRConfigurationC2005Intrasens.RadioButton1010.Click("7;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfigurationC2005Intrasens.Button1' at 46;15.", repo.MyrianRConfigurationC2005Intrasens.Button1Info, new RecordItemIndex(86));
            repo.MyrianRConfigurationC2005Intrasens.Button1.Click("46;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='4436:1CZ8:86ZA:8C1Z:7666:1CFC') on item 'MyrianRConfigurationC2005Intrasens.Text1000'.", repo.MyrianRConfigurationC2005Intrasens.Text1000Info, new RecordItemIndex(87));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Text1000Info, "Text", "4436:1CZ8:86ZA:8C1Z:7666:1CFC");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Annuler') on item 'MyrianRConfigurationC2005Intrasens.Button2'.", repo.MyrianRConfigurationC2005Intrasens.Button2Info, new RecordItemIndex(88));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Button2Info, "Text", "Annuler");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='< &Précédent') on item 'MyrianRConfigurationC2005Intrasens.Button1003'.", repo.MyrianRConfigurationC2005Intrasens.Button1003Info, new RecordItemIndex(89));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Button1003Info, "Text", "< &Précédent");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='&Suivant >') on item 'MyrianRConfigurationC2005Intrasens.Button1'.", repo.MyrianRConfigurationC2005Intrasens.Button1Info, new RecordItemIndex(90));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Button1Info, "Text", "&Suivant >");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfigurationC2005Intrasens.Button2' at 43;17.", repo.MyrianRConfigurationC2005Intrasens.Button2Info, new RecordItemIndex(91));
            repo.MyrianRConfigurationC2005Intrasens.Button2.Click("43;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (ControlId='6') on item 'MyrianRConfiguration.Button6'.", repo.MyrianRConfiguration.Button6Info, new RecordItemIndex(92));
            Validate.Attribute(repo.MyrianRConfiguration.Button6Info, "ControlId", "6");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (ControlId='7') on item 'MyrianRConfiguration.Button7'.", repo.MyrianRConfiguration.Button7Info, new RecordItemIndex(93));
            Validate.Attribute(repo.MyrianRConfiguration.Button7Info, "ControlId", "7");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfiguration.Button7' at 24;12.", repo.MyrianRConfiguration.Button7Info, new RecordItemIndex(94));
            repo.MyrianRConfiguration.Button7.Click("24;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfigurationC2005Intrasens.Button1003' at 35;7.", repo.MyrianRConfigurationC2005Intrasens.Button1003Info, new RecordItemIndex(95));
            repo.MyrianRConfigurationC2005Intrasens.Button1003.Click("35;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MyrianRConfigurationC2005Intrasens.RadioButton1010'.", repo.MyrianRConfigurationC2005Intrasens.RadioButton1010Info, new RecordItemIndex(96));
            Validate.Exists(repo.MyrianRConfigurationC2005Intrasens.RadioButton1010Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfigurationC2005Intrasens.Button1' at 51;2.", repo.MyrianRConfigurationC2005Intrasens.Button1Info, new RecordItemIndex(97));
            repo.MyrianRConfigurationC2005Intrasens.Button1.Click("51;2");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='4436:1CZ8:86ZA:8C1Z:7666:1CFC') on item 'MyrianRConfigurationC2005Intrasens.Text1000'.", repo.MyrianRConfigurationC2005Intrasens.Text1000Info, new RecordItemIndex(98));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Text1000Info, "Text", "4436:1CZ8:86ZA:8C1Z:7666:1CFC");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfigurationC2005Intrasens.Button1' at 25;15.", repo.MyrianRConfigurationC2005Intrasens.Button1Info, new RecordItemIndex(99));
            repo.MyrianRConfigurationC2005Intrasens.Button1.Click("25;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='C:\\ProgramData\\Intrasense\\database') on item 'MyrianRConfigurationC2005Intrasens.Text1002'.", repo.MyrianRConfigurationC2005Intrasens.Text1002Info, new RecordItemIndex(100));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Text1002Info, "Text", "C:\\ProgramData\\Intrasense\\database");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='&P&arcourir...') on item 'MyrianRConfigurationC2005Intrasens.Button1000'.", repo.MyrianRConfigurationC2005Intrasens.Button1000Info, new RecordItemIndex(101));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Button1000Info, "Text", "&P&arcourir...");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='') on item 'MyrianRConfigurationC2005Intrasens.Text1003'.", repo.MyrianRConfigurationC2005Intrasens.Text1003Info, new RecordItemIndex(102));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Text1003Info, "Text", "");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='&P&arcourir...') on item 'MyrianRConfigurationC2005Intrasens.Button1001'.", repo.MyrianRConfigurationC2005Intrasens.Button1001Info, new RecordItemIndex(103));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Button1001Info, "Text", "&P&arcourir...");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Annuler') on item 'MyrianRConfigurationC2005Intrasens.Button2'.", repo.MyrianRConfigurationC2005Intrasens.Button2Info, new RecordItemIndex(104));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Button2Info, "Text", "Annuler");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='< &Précédent') on item 'MyrianRConfigurationC2005Intrasens.Button1003'.", repo.MyrianRConfigurationC2005Intrasens.Button1003Info, new RecordItemIndex(105));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Button1003Info, "Text", "< &Précédent");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='&Suivant >') on item 'MyrianRConfigurationC2005Intrasens.Button1'.", repo.MyrianRConfigurationC2005Intrasens.Button1Info, new RecordItemIndex(106));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Button1Info, "Text", "&Suivant >");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfigurationC2005Intrasens.Button2' at 45;7.", repo.MyrianRConfigurationC2005Intrasens.Button2Info, new RecordItemIndex(107));
            repo.MyrianRConfigurationC2005Intrasens.Button2.Click("45;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (ControlId='6') on item 'MyrianRConfiguration.Button6'.", repo.MyrianRConfiguration.Button6Info, new RecordItemIndex(108));
            Validate.Attribute(repo.MyrianRConfiguration.Button6Info, "ControlId", "6");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (ControlId='7') on item 'MyrianRConfiguration.Button7'.", repo.MyrianRConfiguration.Button7Info, new RecordItemIndex(109));
            Validate.Attribute(repo.MyrianRConfiguration.Button7Info, "ControlId", "7");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfiguration.Button7' at 17;9.", repo.MyrianRConfiguration.Button7Info, new RecordItemIndex(110));
            repo.MyrianRConfiguration.Button7.Click("17;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfigurationC2005Intrasens.Button1003' at 35;10.", repo.MyrianRConfigurationC2005Intrasens.Button1003Info, new RecordItemIndex(111));
            repo.MyrianRConfigurationC2005Intrasens.Button1003.Click("35;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='4436:1CZ8:86ZA:8C1Z:7666:1CFC') on item 'MyrianRConfigurationC2005Intrasens.Text1000'.", repo.MyrianRConfigurationC2005Intrasens.Text1000Info, new RecordItemIndex(112));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Text1000Info, "Text", "4436:1CZ8:86ZA:8C1Z:7666:1CFC");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfigurationC2005Intrasens.Button1' at 48;11.", repo.MyrianRConfigurationC2005Intrasens.Button1Info, new RecordItemIndex(113));
            repo.MyrianRConfigurationC2005Intrasens.Button1.Click("48;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='&P&arcourir...') on item 'MyrianRConfigurationC2005Intrasens.Button1000'.", repo.MyrianRConfigurationC2005Intrasens.Button1000Info, new RecordItemIndex(114));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Button1000Info, "Text", "&P&arcourir...");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfigurationC2005Intrasens.Button1' at 39;7.", repo.MyrianRConfigurationC2005Intrasens.Button1Info, new RecordItemIndex(115));
            repo.MyrianRConfigurationC2005Intrasens.Button1.Click("39;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Par défaut') on item 'MyrianRConfigurationC2005Intrasens.Button1009'.", repo.MyrianRConfigurationC2005Intrasens.Button1009Info, new RecordItemIndex(116));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Button1009Info, "Text", "Par défaut");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='&Utiliser une liste de serveurs existante...') on item 'MyrianRConfigurationC2005Intrasens.Button1008'.", repo.MyrianRConfigurationC2005Intrasens.Button1008Info, new RecordItemIndex(117));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Button1008Info, "Text", "&Utiliser une liste de serveurs existante...");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Annuler') on item 'MyrianRConfigurationC2005Intrasens.Button2'.", repo.MyrianRConfigurationC2005Intrasens.Button2Info, new RecordItemIndex(118));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Button2Info, "Text", "Annuler");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='< &Précédent') on item 'MyrianRConfigurationC2005Intrasens.Button1003'.", repo.MyrianRConfigurationC2005Intrasens.Button1003Info, new RecordItemIndex(119));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Button1003Info, "Text", "< &Précédent");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='&Suivant >') on item 'MyrianRConfigurationC2005Intrasens.Button1'.", repo.MyrianRConfigurationC2005Intrasens.Button1Info, new RecordItemIndex(120));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Button1Info, "Text", "&Suivant >");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfigurationC2005Intrasens.Button2' at 22;16.", repo.MyrianRConfigurationC2005Intrasens.Button2Info, new RecordItemIndex(121));
            repo.MyrianRConfigurationC2005Intrasens.Button2.Click("22;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (ControlId='6') on item 'MyrianRConfiguration.Button6'.", repo.MyrianRConfiguration.Button6Info, new RecordItemIndex(122));
            Validate.Attribute(repo.MyrianRConfiguration.Button6Info, "ControlId", "6");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (ControlId='7') on item 'MyrianRConfiguration.Button7'.", repo.MyrianRConfiguration.Button7Info, new RecordItemIndex(123));
            Validate.Attribute(repo.MyrianRConfiguration.Button7Info, "ControlId", "7");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfiguration.Button7' at 31;12.", repo.MyrianRConfiguration.Button7Info, new RecordItemIndex(124));
            repo.MyrianRConfiguration.Button7.Click("31;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfigurationC2005Intrasens.Button1003' at 30;7.", repo.MyrianRConfigurationC2005Intrasens.Button1003Info, new RecordItemIndex(125));
            repo.MyrianRConfigurationC2005Intrasens.Button1003.Click("30;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='&P&arcourir...') on item 'MyrianRConfigurationC2005Intrasens.Button1000'.", repo.MyrianRConfigurationC2005Intrasens.Button1000Info, new RecordItemIndex(126));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Button1000Info, "Text", "&P&arcourir...");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfigurationC2005Intrasens.Button1' at 52;8.", repo.MyrianRConfigurationC2005Intrasens.Button1Info, new RecordItemIndex(127));
            repo.MyrianRConfigurationC2005Intrasens.Button1.Click("52;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Par défaut') on item 'MyrianRConfigurationC2005Intrasens.Button1009'.", repo.MyrianRConfigurationC2005Intrasens.Button1009Info, new RecordItemIndex(128));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Button1009Info, "Text", "Par défaut");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfigurationC2005Intrasens.Button1' at 64;9.", repo.MyrianRConfigurationC2005Intrasens.Button1Info, new RecordItemIndex(129));
            repo.MyrianRConfigurationC2005Intrasens.Button1.Click("64;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='DBMS') on item 'MyrianRConfigurationC2005Intrasens.Isconfig.Text10041'.", repo.MyrianRConfigurationC2005Intrasens.Isconfig.Text10041Info, new RecordItemIndex(130));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Isconfig.Text10041Info, "Text", "DBMS");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='5679') on item 'MyrianRConfigurationC2005Intrasens.Isconfig.Text10051'.", repo.MyrianRConfigurationC2005Intrasens.Isconfig.Text10051Info, new RecordItemIndex(131));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Isconfig.Text10051Info, "Text", "5679");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='C:\\ProgramData\\Intrasense\\userdata\\hamza.erraji\\temp') on item 'MyrianRConfigurationC2005Intrasens.Text1014'.", repo.MyrianRConfigurationC2005Intrasens.Text1014Info, new RecordItemIndex(132));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Text1014Info, "Text", "C:\\ProgramData\\Intrasense\\userdata\\hamza.erraji\\temp");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='...') on item 'MyrianRConfigurationC2005Intrasens.Button1015'.", repo.MyrianRConfigurationC2005Intrasens.Button1015Info, new RecordItemIndex(133));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Button1015Info, "Text", "...");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='127.0.0.1') on item 'MyrianRConfigurationC2005Intrasens.Isconfig.Text10071'.", repo.MyrianRConfigurationC2005Intrasens.Isconfig.Text10071Info, new RecordItemIndex(134));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Isconfig.Text10071Info, "Text", "127.0.0.1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='6000') on item 'MyrianRConfigurationC2005Intrasens.Isconfig.Text10061'.", repo.MyrianRConfigurationC2005Intrasens.Isconfig.Text10061Info, new RecordItemIndex(135));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Isconfig.Text10061Info, "Text", "6000");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='False') on item 'MyrianRConfigurationC2005Intrasens.CheckBox1013'.", repo.MyrianRConfigurationC2005Intrasens.CheckBox1013Info, new RecordItemIndex(136));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.CheckBox1013Info, "Checked", "False");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Annuler') on item 'MyrianRConfigurationC2005Intrasens.Button2'.", repo.MyrianRConfigurationC2005Intrasens.Button2Info, new RecordItemIndex(137));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Button2Info, "Text", "Annuler");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='< &Précédent') on item 'MyrianRConfigurationC2005Intrasens.Button1003'.", repo.MyrianRConfigurationC2005Intrasens.Button1003Info, new RecordItemIndex(138));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Button1003Info, "Text", "< &Précédent");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='&Terminer') on item 'MyrianRConfigurationC2005Intrasens.Button1'.", repo.MyrianRConfigurationC2005Intrasens.Button1Info, new RecordItemIndex(139));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Button1Info, "Text", "&Terminer");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfigurationC2005Intrasens.Button2' at 48;10.", repo.MyrianRConfigurationC2005Intrasens.Button2Info, new RecordItemIndex(140));
            repo.MyrianRConfigurationC2005Intrasens.Button2.Click("48;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (ControlId='6') on item 'MyrianRConfiguration.Button6'.", repo.MyrianRConfiguration.Button6Info, new RecordItemIndex(141));
            Validate.Attribute(repo.MyrianRConfiguration.Button6Info, "ControlId", "6");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (ControlId='7') on item 'MyrianRConfiguration.Button7'.", repo.MyrianRConfiguration.Button7Info, new RecordItemIndex(142));
            Validate.Attribute(repo.MyrianRConfiguration.Button7Info, "ControlId", "7");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfiguration.Button7' at 27;12.", repo.MyrianRConfiguration.Button7Info, new RecordItemIndex(143));
            repo.MyrianRConfiguration.Button7.Click("27;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='False') on item 'MyrianRConfigurationC2005Intrasens.CheckBox1013'.", repo.MyrianRConfigurationC2005Intrasens.CheckBox1013Info, new RecordItemIndex(144));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.CheckBox1013Info, "Checked", "False");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfigurationC2005Intrasens.Button1003' at 35;10.", repo.MyrianRConfigurationC2005Intrasens.Button1003Info, new RecordItemIndex(145));
            repo.MyrianRConfigurationC2005Intrasens.Button1003.Click("35;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Par défaut') on item 'MyrianRConfigurationC2005Intrasens.Button1009'.", repo.MyrianRConfigurationC2005Intrasens.Button1009Info, new RecordItemIndex(146));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.Button1009Info, "Text", "Par défaut");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfigurationC2005Intrasens.Button1' at 64;10.", repo.MyrianRConfigurationC2005Intrasens.Button1Info, new RecordItemIndex(147));
            repo.MyrianRConfigurationC2005Intrasens.Button1.Click("64;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='False') on item 'MyrianRConfigurationC2005Intrasens.CheckBox1013'.", repo.MyrianRConfigurationC2005Intrasens.CheckBox1013Info, new RecordItemIndex(148));
            Validate.Attribute(repo.MyrianRConfigurationC2005Intrasens.CheckBox1013Info, "Checked", "False");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyrianRConfigurationC2005Intrasens.Button1' at 44;8.", repo.MyrianRConfigurationC2005Intrasens.Button1Info, new RecordItemIndex(149));
            repo.MyrianRConfigurationC2005Intrasens.Button1.Click("44;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='WixUI_Bmp_Dialog') on item 'InstallationDeMyrian.Text322'.", repo.InstallationDeMyrian.Text322Info, new RecordItemIndex(150));
            Validate.Attribute(repo.InstallationDeMyrian.Text322Info, "Text", "WixUI_Bmp_Dialog");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='&Terminer') on item 'InstallationDeMyrian.Button350'.", repo.InstallationDeMyrian.Button350Info, new RecordItemIndex(151));
            Validate.Attribute(repo.InstallationDeMyrian.Button350Info, "Text", "&Terminer");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InstallationDeMyrian.Button350' at 28;13.", repo.InstallationDeMyrian.Button350Info, new RecordItemIndex(152));
            repo.InstallationDeMyrian.Button350.Click("28;13");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
