///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace setupMyrian_complexFlow
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the setupMyrian_complexFlowRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("db8db7e3-4e82-45a7-8489-d51b5e5bca05")]
    public partial class setupMyrian_complexFlowRepository : RepoGenBaseFolder
    {
        static setupMyrian_complexFlowRepository instance = new setupMyrian_complexFlowRepository();
        setupMyrian_complexFlowRepositoryFolders.MyrianR2010IntrasenseAppFolder _myrianr2010intrasense;
        setupMyrian_complexFlowRepositoryFolders.InstallationDeMyrianAppFolder _installationdemyrian;
        setupMyrian_complexFlowRepositoryFolders.MyrianRConfigurationC2005IntrasensAppFolder _myrianrconfigurationc2005intrasens;
        setupMyrian_complexFlowRepositoryFolders.MyrianRConfigurationAppFolder _myrianrconfiguration;
        setupMyrian_complexFlowRepositoryFolders.MyrianR200OuvertureDeSessionAppFolder _myrianr200ouverturedesession;
        setupMyrian_complexFlowRepositoryFolders.MyrianRAppFolder _myrianr;
        setupMyrian_complexFlowRepositoryFolders.MyrianRCalibrationEcranC2005IntraAppFolder _myrianrcalibrationecranc2005intra;
        setupMyrian_complexFlowRepositoryFolders.ContratDeLicenceEULAAppFolder _contratdelicenceeula;
        setupMyrian_complexFlowRepositoryFolders.MyrianR200AppFolder _myrianr200;

        /// <summary>
        /// Gets the singleton class instance representing the setupMyrian_complexFlowRepository element repository.
        /// </summary>
        [RepositoryFolder("db8db7e3-4e82-45a7-8489-d51b5e5bca05")]
        public static setupMyrian_complexFlowRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public setupMyrian_complexFlowRepository() 
            : base("setupMyrian_complexFlowRepository", "/", null, 0, false, "db8db7e3-4e82-45a7-8489-d51b5e5bca05", ".\\RepositoryImages\\setupMyrian_complexFlowRepositorydb8db7e3.rximgres")
        {
            _myrianr2010intrasense = new setupMyrian_complexFlowRepositoryFolders.MyrianR2010IntrasenseAppFolder(this);
            _installationdemyrian = new setupMyrian_complexFlowRepositoryFolders.InstallationDeMyrianAppFolder(this);
            _myrianrconfigurationc2005intrasens = new setupMyrian_complexFlowRepositoryFolders.MyrianRConfigurationC2005IntrasensAppFolder(this);
            _myrianrconfiguration = new setupMyrian_complexFlowRepositoryFolders.MyrianRConfigurationAppFolder(this);
            _myrianr200ouverturedesession = new setupMyrian_complexFlowRepositoryFolders.MyrianR200OuvertureDeSessionAppFolder(this);
            _myrianr = new setupMyrian_complexFlowRepositoryFolders.MyrianRAppFolder(this);
            _myrianrcalibrationecranc2005intra = new setupMyrian_complexFlowRepositoryFolders.MyrianRCalibrationEcranC2005IntraAppFolder(this);
            _contratdelicenceeula = new setupMyrian_complexFlowRepositoryFolders.ContratDeLicenceEULAAppFolder(this);
            _myrianr200 = new setupMyrian_complexFlowRepositoryFolders.MyrianR200AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("db8db7e3-4e82-45a7-8489-d51b5e5bca05")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MyrianR2010Intrasense folder.
        /// </summary>
        [RepositoryFolder("73e66c68-e966-46ac-9e99-40b5230ee7fa")]
        public virtual setupMyrian_complexFlowRepositoryFolders.MyrianR2010IntrasenseAppFolder MyrianR2010Intrasense
        {
            get { return _myrianr2010intrasense; }
        }

        /// <summary>
        /// The InstallationDeMyrian folder.
        /// </summary>
        [RepositoryFolder("7e9bb812-3dd1-4d70-987d-15df6d67f89b")]
        public virtual setupMyrian_complexFlowRepositoryFolders.InstallationDeMyrianAppFolder InstallationDeMyrian
        {
            get { return _installationdemyrian; }
        }

        /// <summary>
        /// The MyrianRConfigurationC2005Intrasens folder.
        /// </summary>
        [RepositoryFolder("b645cd9f-9e5d-46eb-a202-94b46f2fca95")]
        public virtual setupMyrian_complexFlowRepositoryFolders.MyrianRConfigurationC2005IntrasensAppFolder MyrianRConfigurationC2005Intrasens
        {
            get { return _myrianrconfigurationc2005intrasens; }
        }

        /// <summary>
        /// The MyrianRConfiguration folder.
        /// </summary>
        [RepositoryFolder("e2c8eff0-b367-4055-9105-3fa08a94f2f9")]
        public virtual setupMyrian_complexFlowRepositoryFolders.MyrianRConfigurationAppFolder MyrianRConfiguration
        {
            get { return _myrianrconfiguration; }
        }

        /// <summary>
        /// The MyrianR200OuvertureDeSession folder.
        /// </summary>
        [RepositoryFolder("d02722bc-8a53-4579-ad5d-9e5d9fda9320")]
        public virtual setupMyrian_complexFlowRepositoryFolders.MyrianR200OuvertureDeSessionAppFolder MyrianR200OuvertureDeSession
        {
            get { return _myrianr200ouverturedesession; }
        }

        /// <summary>
        /// The MyrianR folder.
        /// </summary>
        [RepositoryFolder("50db8392-3d5e-44a1-beaa-bdd1eff0d31f")]
        public virtual setupMyrian_complexFlowRepositoryFolders.MyrianRAppFolder MyrianR
        {
            get { return _myrianr; }
        }

        /// <summary>
        /// The MyrianRCalibrationEcranC2005Intra folder.
        /// </summary>
        [RepositoryFolder("be9bb14f-4633-4a2c-9a16-71cc5cfbd142")]
        public virtual setupMyrian_complexFlowRepositoryFolders.MyrianRCalibrationEcranC2005IntraAppFolder MyrianRCalibrationEcranC2005Intra
        {
            get { return _myrianrcalibrationecranc2005intra; }
        }

        /// <summary>
        /// The ContratDeLicenceEULA folder.
        /// </summary>
        [RepositoryFolder("373ba717-f1fb-482f-a330-a49817b14f28")]
        public virtual setupMyrian_complexFlowRepositoryFolders.ContratDeLicenceEULAAppFolder ContratDeLicenceEULA
        {
            get { return _contratdelicenceeula; }
        }

        /// <summary>
        /// The MyrianR200 folder.
        /// </summary>
        [RepositoryFolder("9ba5d511-ddeb-48c4-adb2-c8dfffa3478e")]
        public virtual setupMyrian_complexFlowRepositoryFolders.MyrianR200AppFolder MyrianR200
        {
            get { return _myrianr200; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class setupMyrian_complexFlowRepositoryFolders
    {
        /// <summary>
        /// The MyrianR2010IntrasenseAppFolder folder.
        /// </summary>
        [RepositoryFolder("73e66c68-e966-46ac-9e99-40b5230ee7fa")]
        public partial class MyrianR2010IntrasenseAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _checkbox410Info;
            RepoItemInfo _combobox400Info;
            RepoItemInfo _button1Info;
            RepoItemInfo _button2Info;

            /// <summary>
            /// Creates a new MyrianR2010Intrasense  folder.
            /// </summary>
            public MyrianR2010IntrasenseAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MyrianR2010Intrasense", "/form[@title='Myrian® 2010 Intrasense']", parentFolder, 30000, null, false, "73e66c68-e966-46ac-9e99-40b5230ee7fa", "")
            {
                _checkbox410Info = new RepoItemInfo(this, "CheckBox410", "checkbox[@controlid='410']", 30000, null, "71573a1c-9adf-44d4-bf40-505354b15239");
                _combobox400Info = new RepoItemInfo(this, "ComboBox400", "combobox[@controlid='400']", 30000, null, "344d5550-862b-4b95-8231-559f31d8d3fe");
                _button1Info = new RepoItemInfo(this, "Button1", "button[@controlid='1']", 30000, null, "c2e63e1d-25e1-42c4-893f-796edf3cf071");
                _button2Info = new RepoItemInfo(this, "Button2", "button[@controlid='2']", 30000, null, "83391648-41ad-43c5-8c62-8f25a69f06fe");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("73e66c68-e966-46ac-9e99-40b5230ee7fa")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("73e66c68-e966-46ac-9e99-40b5230ee7fa")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CheckBox410 item.
            /// </summary>
            [RepositoryItem("71573a1c-9adf-44d4-bf40-505354b15239")]
            public virtual Ranorex.CheckBox CheckBox410
            {
                get
                {
                    return _checkbox410Info.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The CheckBox410 item info.
            /// </summary>
            [RepositoryItemInfo("71573a1c-9adf-44d4-bf40-505354b15239")]
            public virtual RepoItemInfo CheckBox410Info
            {
                get
                {
                    return _checkbox410Info;
                }
            }

            /// <summary>
            /// The ComboBox400 item.
            /// </summary>
            [RepositoryItem("344d5550-862b-4b95-8231-559f31d8d3fe")]
            public virtual Ranorex.ComboBox ComboBox400
            {
                get
                {
                    return _combobox400Info.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ComboBox400 item info.
            /// </summary>
            [RepositoryItemInfo("344d5550-862b-4b95-8231-559f31d8d3fe")]
            public virtual RepoItemInfo ComboBox400Info
            {
                get
                {
                    return _combobox400Info;
                }
            }

            /// <summary>
            /// The Button1 item.
            /// </summary>
            [RepositoryItem("c2e63e1d-25e1-42c4-893f-796edf3cf071")]
            public virtual Ranorex.Button Button1
            {
                get
                {
                    return _button1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1 item info.
            /// </summary>
            [RepositoryItemInfo("c2e63e1d-25e1-42c4-893f-796edf3cf071")]
            public virtual RepoItemInfo Button1Info
            {
                get
                {
                    return _button1Info;
                }
            }

            /// <summary>
            /// The Button2 item.
            /// </summary>
            [RepositoryItem("83391648-41ad-43c5-8c62-8f25a69f06fe")]
            public virtual Ranorex.Button Button2
            {
                get
                {
                    return _button2Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button2 item info.
            /// </summary>
            [RepositoryItemInfo("83391648-41ad-43c5-8c62-8f25a69f06fe")]
            public virtual RepoItemInfo Button2Info
            {
                get
                {
                    return _button2Info;
                }
            }
        }

        /// <summary>
        /// The InstallationDeMyrianAppFolder folder.
        /// </summary>
        [RepositoryFolder("7e9bb812-3dd1-4d70-987d-15df6d67f89b")]
        public partial class InstallationDeMyrianAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text322Info;
            RepoItemInfo _button374Info;
            RepoItemInfo _button311Info;
            RepoItemInfo _button380Info;
            RepoItemInfo _button379Info;
            RepoItemInfo _text441Info;
            RepoItemInfo _button445Info;
            RepoItemInfo _button352Info;
            RepoItemInfo _button408Info;
            RepoItemInfo _text460Info;
            RepoItemInfo _text383Info;
            RepoItemInfo _button350Info;

            /// <summary>
            /// Creates a new InstallationDeMyrian  folder.
            /// </summary>
            public InstallationDeMyrianAppFolder(RepoGenBaseFolder parentFolder) :
                    base("InstallationDeMyrian", "/form[@title='Installation de Myrian']", parentFolder, 30000, null, false, "7e9bb812-3dd1-4d70-987d-15df6d67f89b", "")
            {
                _text322Info = new RepoItemInfo(this, "Text322", "text[@controlid='322']", 30000, null, "7c5c5f29-d40d-40a0-ba78-e92d35a1cf84");
                _button374Info = new RepoItemInfo(this, "Button374", "button[@controlid='374']", 30000, null, "8ec6b82d-6b84-4d64-ad6b-cdeaadafa014");
                _button311Info = new RepoItemInfo(this, "Button311", "button[@controlid='311']", 30000, null, "08ff491f-4a3a-49df-9f0e-7cccee0a1aad");
                _button380Info = new RepoItemInfo(this, "Button380", "button[@controlid='380']", 30000, null, "34155660-1c5c-4024-888d-de4f701efec4");
                _button379Info = new RepoItemInfo(this, "Button379", "button[@controlid='379']", 30000, null, "c3ffcc14-c1df-4aa3-a1b8-a17e1ac826d3");
                _text441Info = new RepoItemInfo(this, "Text441", "text[@controlid='441']", 30000, null, "f1ba4b98-e0ea-41e0-a0d0-de104c376300");
                _button445Info = new RepoItemInfo(this, "Button445", "button[@controlid='445']", 30000, null, "636120a6-ebad-431f-8250-12d80c87d419");
                _button352Info = new RepoItemInfo(this, "Button352", "button[@controlid='352']", 30000, null, "1b22c179-b13f-4fb4-be87-4814a10e90c7");
                _button408Info = new RepoItemInfo(this, "Button408", "button[@controlid='408']", 30000, null, "f5f74d36-f351-4165-b707-5a11bc3607fd");
                _text460Info = new RepoItemInfo(this, "Text460", "text[@controlid='460']", 30000, null, "f1d6a7ac-2ef2-4ed8-b0ab-f0b104a804db");
                _text383Info = new RepoItemInfo(this, "Text383", "text[@controlid='383']", 30000, null, "b998a9a2-cf65-44b6-b66e-45958217f367");
                _button350Info = new RepoItemInfo(this, "Button350", "button[@controlid='350']", 30000, null, "3afd0653-4e7f-455c-b0d7-e2212ca8f264");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7e9bb812-3dd1-4d70-987d-15df6d67f89b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7e9bb812-3dd1-4d70-987d-15df6d67f89b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text322 item.
            /// </summary>
            [RepositoryItem("7c5c5f29-d40d-40a0-ba78-e92d35a1cf84")]
            public virtual Ranorex.Text Text322
            {
                get
                {
                    return _text322Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text322 item info.
            /// </summary>
            [RepositoryItemInfo("7c5c5f29-d40d-40a0-ba78-e92d35a1cf84")]
            public virtual RepoItemInfo Text322Info
            {
                get
                {
                    return _text322Info;
                }
            }

            /// <summary>
            /// The Button374 item.
            /// </summary>
            [RepositoryItem("8ec6b82d-6b84-4d64-ad6b-cdeaadafa014")]
            public virtual Ranorex.Button Button374
            {
                get
                {
                    return _button374Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button374 item info.
            /// </summary>
            [RepositoryItemInfo("8ec6b82d-6b84-4d64-ad6b-cdeaadafa014")]
            public virtual RepoItemInfo Button374Info
            {
                get
                {
                    return _button374Info;
                }
            }

            /// <summary>
            /// The Button311 item.
            /// </summary>
            [RepositoryItem("08ff491f-4a3a-49df-9f0e-7cccee0a1aad")]
            public virtual Ranorex.Button Button311
            {
                get
                {
                    return _button311Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button311 item info.
            /// </summary>
            [RepositoryItemInfo("08ff491f-4a3a-49df-9f0e-7cccee0a1aad")]
            public virtual RepoItemInfo Button311Info
            {
                get
                {
                    return _button311Info;
                }
            }

            /// <summary>
            /// The Button380 item.
            /// </summary>
            [RepositoryItem("34155660-1c5c-4024-888d-de4f701efec4")]
            public virtual Ranorex.Button Button380
            {
                get
                {
                    return _button380Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button380 item info.
            /// </summary>
            [RepositoryItemInfo("34155660-1c5c-4024-888d-de4f701efec4")]
            public virtual RepoItemInfo Button380Info
            {
                get
                {
                    return _button380Info;
                }
            }

            /// <summary>
            /// The Button379 item.
            /// </summary>
            [RepositoryItem("c3ffcc14-c1df-4aa3-a1b8-a17e1ac826d3")]
            public virtual Ranorex.Button Button379
            {
                get
                {
                    return _button379Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button379 item info.
            /// </summary>
            [RepositoryItemInfo("c3ffcc14-c1df-4aa3-a1b8-a17e1ac826d3")]
            public virtual RepoItemInfo Button379Info
            {
                get
                {
                    return _button379Info;
                }
            }

            /// <summary>
            /// The Text441 item.
            /// </summary>
            [RepositoryItem("f1ba4b98-e0ea-41e0-a0d0-de104c376300")]
            public virtual Ranorex.Text Text441
            {
                get
                {
                    return _text441Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text441 item info.
            /// </summary>
            [RepositoryItemInfo("f1ba4b98-e0ea-41e0-a0d0-de104c376300")]
            public virtual RepoItemInfo Text441Info
            {
                get
                {
                    return _text441Info;
                }
            }

            /// <summary>
            /// The Button445 item.
            /// </summary>
            [RepositoryItem("636120a6-ebad-431f-8250-12d80c87d419")]
            public virtual Ranorex.Button Button445
            {
                get
                {
                    return _button445Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button445 item info.
            /// </summary>
            [RepositoryItemInfo("636120a6-ebad-431f-8250-12d80c87d419")]
            public virtual RepoItemInfo Button445Info
            {
                get
                {
                    return _button445Info;
                }
            }

            /// <summary>
            /// The Button352 item.
            /// </summary>
            [RepositoryItem("1b22c179-b13f-4fb4-be87-4814a10e90c7")]
            public virtual Ranorex.Button Button352
            {
                get
                {
                    return _button352Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button352 item info.
            /// </summary>
            [RepositoryItemInfo("1b22c179-b13f-4fb4-be87-4814a10e90c7")]
            public virtual RepoItemInfo Button352Info
            {
                get
                {
                    return _button352Info;
                }
            }

            /// <summary>
            /// The Button408 item.
            /// </summary>
            [RepositoryItem("f5f74d36-f351-4165-b707-5a11bc3607fd")]
            public virtual Ranorex.Button Button408
            {
                get
                {
                    return _button408Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button408 item info.
            /// </summary>
            [RepositoryItemInfo("f5f74d36-f351-4165-b707-5a11bc3607fd")]
            public virtual RepoItemInfo Button408Info
            {
                get
                {
                    return _button408Info;
                }
            }

            /// <summary>
            /// The Text460 item.
            /// </summary>
            [RepositoryItem("f1d6a7ac-2ef2-4ed8-b0ab-f0b104a804db")]
            public virtual Ranorex.Text Text460
            {
                get
                {
                    return _text460Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text460 item info.
            /// </summary>
            [RepositoryItemInfo("f1d6a7ac-2ef2-4ed8-b0ab-f0b104a804db")]
            public virtual RepoItemInfo Text460Info
            {
                get
                {
                    return _text460Info;
                }
            }

            /// <summary>
            /// The Text383 item.
            /// </summary>
            [RepositoryItem("b998a9a2-cf65-44b6-b66e-45958217f367")]
            public virtual Ranorex.Text Text383
            {
                get
                {
                    return _text383Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text383 item info.
            /// </summary>
            [RepositoryItemInfo("b998a9a2-cf65-44b6-b66e-45958217f367")]
            public virtual RepoItemInfo Text383Info
            {
                get
                {
                    return _text383Info;
                }
            }

            /// <summary>
            /// The Button350 item.
            /// </summary>
            [RepositoryItem("3afd0653-4e7f-455c-b0d7-e2212ca8f264")]
            public virtual Ranorex.Button Button350
            {
                get
                {
                    return _button350Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button350 item info.
            /// </summary>
            [RepositoryItemInfo("3afd0653-4e7f-455c-b0d7-e2212ca8f264")]
            public virtual RepoItemInfo Button350Info
            {
                get
                {
                    return _button350Info;
                }
            }
        }

        /// <summary>
        /// The MyrianRConfigurationC2005IntrasensAppFolder folder.
        /// </summary>
        [RepositoryFolder("b645cd9f-9e5d-46eb-a202-94b46f2fca95")]
        public partial class MyrianRConfigurationC2005IntrasensAppFolder : RepoGenBaseFolder
        {
            setupMyrian_complexFlowRepositoryFolders.IsconfigFolder _isconfig;
            RepoItemInfo _text1004Info;
            RepoItemInfo _text1005Info;
            RepoItemInfo _text1006Info;
            RepoItemInfo _text1007Info;
            RepoItemInfo _text1008Info;
            RepoItemInfo _text1009Info;
            RepoItemInfo _button1016Info;
            RepoItemInfo _button2Info;
            RepoItemInfo _button1Info;
            RepoItemInfo _radiobutton1010Info;
            RepoItemInfo _radiobutton1011Info;
            RepoItemInfo _button1003Info;
            RepoItemInfo _text1000Info;
            RepoItemInfo _text1002Info;
            RepoItemInfo _button1000Info;
            RepoItemInfo _text1003Info;
            RepoItemInfo _button1001Info;
            RepoItemInfo _button1009Info;
            RepoItemInfo _button1008Info;
            RepoItemInfo _text1014Info;
            RepoItemInfo _button1015Info;
            RepoItemInfo _checkbox1013Info;

            /// <summary>
            /// Creates a new MyrianRConfigurationC2005Intrasens  folder.
            /// </summary>
            public MyrianRConfigurationC2005IntrasensAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MyrianRConfigurationC2005Intrasens", "/form[@title~'^Myrian®\\ Configuration\\ \\(C\\)']", parentFolder, 30000, null, false, "b645cd9f-9e5d-46eb-a202-94b46f2fca95", "")
            {
                _isconfig = new setupMyrian_complexFlowRepositoryFolders.IsconfigFolder(this);
                _text1004Info = new RepoItemInfo(this, "Text1004", "?/?/text[@controlid='1004']", 30000, null, "03439ec2-527f-4e33-bc1b-df04f45246ba");
                _text1005Info = new RepoItemInfo(this, "Text1005", "?/?/text[@controlid='1005']", 30000, null, "f8b30139-3a13-4724-af83-d812b16075ee");
                _text1006Info = new RepoItemInfo(this, "Text1006", "?/?/text[@controlid='1006']", 30000, null, "4830162b-1824-4996-9ae4-626ce84509eb");
                _text1007Info = new RepoItemInfo(this, "Text1007", "?/?/text[@controlid='1007']", 30000, null, "f7018cb8-e9f2-422d-b19a-b8fadb552693");
                _text1008Info = new RepoItemInfo(this, "Text1008", "?/?/text[@controlid='1008']", 30000, null, "e6a893d7-578b-4762-8ad2-72a1b8aba62b");
                _text1009Info = new RepoItemInfo(this, "Text1009", "?/?/text[@controlid='1009']", 30000, null, "7b7c1f5b-7d09-4f18-89b2-2c23a5424244");
                _button1016Info = new RepoItemInfo(this, "Button1016", "?/?/button[@controlid='1016']", 30000, null, "fd7610ee-58ad-4984-a484-c286d8feff8f");
                _button2Info = new RepoItemInfo(this, "Button2", "button[@controlid='2']", 30000, null, "3581af46-335b-4a13-896f-e153f3db8ad4");
                _button1Info = new RepoItemInfo(this, "Button1", "button[@controlid='1']", 30000, null, "9267de8c-f533-4e8e-abd0-64fbcc223021");
                _radiobutton1010Info = new RepoItemInfo(this, "RadioButton1010", "?/?/radiobutton[@controlid='1010']", 30000, null, "a644fea3-450d-478c-94de-ed690605ec64");
                _radiobutton1011Info = new RepoItemInfo(this, "RadioButton1011", "?/?/radiobutton[@controlid='1011']", 30000, null, "05374d29-e12f-4c5a-86c3-292d7edf40be");
                _button1003Info = new RepoItemInfo(this, "Button1003", "button[@controlid='1003']", 30000, null, "bfa38fbf-1cd6-4140-b0d6-aaf920393781");
                _text1000Info = new RepoItemInfo(this, "Text1000", "?/?/text[@controlid='1000']", 30000, null, "614bda5a-3533-48b8-a550-d3edfcc1e20e");
                _text1002Info = new RepoItemInfo(this, "Text1002", "?/?/text[@controlid='1002']", 30000, null, "3b676c7f-c1c6-4cc4-9854-3ca3a3db2c2e");
                _button1000Info = new RepoItemInfo(this, "Button1000", "?/?/button[@controlid='1000']", 30000, null, "3d063372-5a5f-45b6-9ae5-62385e152ee4");
                _text1003Info = new RepoItemInfo(this, "Text1003", "?/?/text[@controlid='1003']", 30000, null, "716a90d3-5a66-40bb-b89a-6ff5ac363af4");
                _button1001Info = new RepoItemInfo(this, "Button1001", "?/?/button[@controlid='1001']", 30000, null, "b12677d5-b8a9-4215-ae03-df6b12504578");
                _button1009Info = new RepoItemInfo(this, "Button1009", "?/?/button[@controlid='1009']", 30000, null, "ac3382a7-5d80-46dd-ac14-c2a2616a5535");
                _button1008Info = new RepoItemInfo(this, "Button1008", "?/?/button[@controlid='1008']", 30000, null, "a712cb93-0819-4d4d-b36c-c6e66090fe08");
                _text1014Info = new RepoItemInfo(this, "Text1014", "?/?/text[@controlid='1014']", 30000, null, "38df9221-e1a6-41e0-be29-4d2a2984470a");
                _button1015Info = new RepoItemInfo(this, "Button1015", "?/?/button[@controlid='1015']", 30000, null, "873e1bcd-5d79-462d-9a30-e5680d423b1b");
                _checkbox1013Info = new RepoItemInfo(this, "CheckBox1013", "?/?/checkbox[@controlid='1013']", 30000, null, "81650e56-03b2-447d-8514-e0a9db6d9fa5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b645cd9f-9e5d-46eb-a202-94b46f2fca95")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b645cd9f-9e5d-46eb-a202-94b46f2fca95")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text1004 item.
            /// </summary>
            [RepositoryItem("03439ec2-527f-4e33-bc1b-df04f45246ba")]
            public virtual Ranorex.Text Text1004
            {
                get
                {
                    return _text1004Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1004 item info.
            /// </summary>
            [RepositoryItemInfo("03439ec2-527f-4e33-bc1b-df04f45246ba")]
            public virtual RepoItemInfo Text1004Info
            {
                get
                {
                    return _text1004Info;
                }
            }

            /// <summary>
            /// The Text1005 item.
            /// </summary>
            [RepositoryItem("f8b30139-3a13-4724-af83-d812b16075ee")]
            public virtual Ranorex.Text Text1005
            {
                get
                {
                    return _text1005Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1005 item info.
            /// </summary>
            [RepositoryItemInfo("f8b30139-3a13-4724-af83-d812b16075ee")]
            public virtual RepoItemInfo Text1005Info
            {
                get
                {
                    return _text1005Info;
                }
            }

            /// <summary>
            /// The Text1006 item.
            /// </summary>
            [RepositoryItem("4830162b-1824-4996-9ae4-626ce84509eb")]
            public virtual Ranorex.Text Text1006
            {
                get
                {
                    return _text1006Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1006 item info.
            /// </summary>
            [RepositoryItemInfo("4830162b-1824-4996-9ae4-626ce84509eb")]
            public virtual RepoItemInfo Text1006Info
            {
                get
                {
                    return _text1006Info;
                }
            }

            /// <summary>
            /// The Text1007 item.
            /// </summary>
            [RepositoryItem("f7018cb8-e9f2-422d-b19a-b8fadb552693")]
            public virtual Ranorex.Text Text1007
            {
                get
                {
                    return _text1007Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1007 item info.
            /// </summary>
            [RepositoryItemInfo("f7018cb8-e9f2-422d-b19a-b8fadb552693")]
            public virtual RepoItemInfo Text1007Info
            {
                get
                {
                    return _text1007Info;
                }
            }

            /// <summary>
            /// The Text1008 item.
            /// </summary>
            [RepositoryItem("e6a893d7-578b-4762-8ad2-72a1b8aba62b")]
            public virtual Ranorex.Text Text1008
            {
                get
                {
                    return _text1008Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1008 item info.
            /// </summary>
            [RepositoryItemInfo("e6a893d7-578b-4762-8ad2-72a1b8aba62b")]
            public virtual RepoItemInfo Text1008Info
            {
                get
                {
                    return _text1008Info;
                }
            }

            /// <summary>
            /// The Text1009 item.
            /// </summary>
            [RepositoryItem("7b7c1f5b-7d09-4f18-89b2-2c23a5424244")]
            public virtual Ranorex.Text Text1009
            {
                get
                {
                    return _text1009Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1009 item info.
            /// </summary>
            [RepositoryItemInfo("7b7c1f5b-7d09-4f18-89b2-2c23a5424244")]
            public virtual RepoItemInfo Text1009Info
            {
                get
                {
                    return _text1009Info;
                }
            }

            /// <summary>
            /// The Button1016 item.
            /// </summary>
            [RepositoryItem("fd7610ee-58ad-4984-a484-c286d8feff8f")]
            public virtual Ranorex.Button Button1016
            {
                get
                {
                    return _button1016Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1016 item info.
            /// </summary>
            [RepositoryItemInfo("fd7610ee-58ad-4984-a484-c286d8feff8f")]
            public virtual RepoItemInfo Button1016Info
            {
                get
                {
                    return _button1016Info;
                }
            }

            /// <summary>
            /// The Button2 item.
            /// </summary>
            [RepositoryItem("3581af46-335b-4a13-896f-e153f3db8ad4")]
            public virtual Ranorex.Button Button2
            {
                get
                {
                    return _button2Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button2 item info.
            /// </summary>
            [RepositoryItemInfo("3581af46-335b-4a13-896f-e153f3db8ad4")]
            public virtual RepoItemInfo Button2Info
            {
                get
                {
                    return _button2Info;
                }
            }

            /// <summary>
            /// The Button1 item.
            /// </summary>
            [RepositoryItem("9267de8c-f533-4e8e-abd0-64fbcc223021")]
            public virtual Ranorex.Button Button1
            {
                get
                {
                    return _button1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1 item info.
            /// </summary>
            [RepositoryItemInfo("9267de8c-f533-4e8e-abd0-64fbcc223021")]
            public virtual RepoItemInfo Button1Info
            {
                get
                {
                    return _button1Info;
                }
            }

            /// <summary>
            /// The RadioButton1010 item.
            /// </summary>
            [RepositoryItem("a644fea3-450d-478c-94de-ed690605ec64")]
            public virtual Ranorex.RadioButton RadioButton1010
            {
                get
                {
                    return _radiobutton1010Info.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RadioButton1010 item info.
            /// </summary>
            [RepositoryItemInfo("a644fea3-450d-478c-94de-ed690605ec64")]
            public virtual RepoItemInfo RadioButton1010Info
            {
                get
                {
                    return _radiobutton1010Info;
                }
            }

            /// <summary>
            /// The RadioButton1011 item.
            /// </summary>
            [RepositoryItem("05374d29-e12f-4c5a-86c3-292d7edf40be")]
            public virtual Ranorex.RadioButton RadioButton1011
            {
                get
                {
                    return _radiobutton1011Info.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RadioButton1011 item info.
            /// </summary>
            [RepositoryItemInfo("05374d29-e12f-4c5a-86c3-292d7edf40be")]
            public virtual RepoItemInfo RadioButton1011Info
            {
                get
                {
                    return _radiobutton1011Info;
                }
            }

            /// <summary>
            /// The Button1003 item.
            /// </summary>
            [RepositoryItem("bfa38fbf-1cd6-4140-b0d6-aaf920393781")]
            public virtual Ranorex.Button Button1003
            {
                get
                {
                    return _button1003Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1003 item info.
            /// </summary>
            [RepositoryItemInfo("bfa38fbf-1cd6-4140-b0d6-aaf920393781")]
            public virtual RepoItemInfo Button1003Info
            {
                get
                {
                    return _button1003Info;
                }
            }

            /// <summary>
            /// The Text1000 item.
            /// </summary>
            [RepositoryItem("614bda5a-3533-48b8-a550-d3edfcc1e20e")]
            public virtual Ranorex.Text Text1000
            {
                get
                {
                    return _text1000Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1000 item info.
            /// </summary>
            [RepositoryItemInfo("614bda5a-3533-48b8-a550-d3edfcc1e20e")]
            public virtual RepoItemInfo Text1000Info
            {
                get
                {
                    return _text1000Info;
                }
            }

            /// <summary>
            /// The Text1002 item.
            /// </summary>
            [RepositoryItem("3b676c7f-c1c6-4cc4-9854-3ca3a3db2c2e")]
            public virtual Ranorex.Text Text1002
            {
                get
                {
                    return _text1002Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1002 item info.
            /// </summary>
            [RepositoryItemInfo("3b676c7f-c1c6-4cc4-9854-3ca3a3db2c2e")]
            public virtual RepoItemInfo Text1002Info
            {
                get
                {
                    return _text1002Info;
                }
            }

            /// <summary>
            /// The Button1000 item.
            /// </summary>
            [RepositoryItem("3d063372-5a5f-45b6-9ae5-62385e152ee4")]
            public virtual Ranorex.Button Button1000
            {
                get
                {
                    return _button1000Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1000 item info.
            /// </summary>
            [RepositoryItemInfo("3d063372-5a5f-45b6-9ae5-62385e152ee4")]
            public virtual RepoItemInfo Button1000Info
            {
                get
                {
                    return _button1000Info;
                }
            }

            /// <summary>
            /// The Text1003 item.
            /// </summary>
            [RepositoryItem("716a90d3-5a66-40bb-b89a-6ff5ac363af4")]
            public virtual Ranorex.Text Text1003
            {
                get
                {
                    return _text1003Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1003 item info.
            /// </summary>
            [RepositoryItemInfo("716a90d3-5a66-40bb-b89a-6ff5ac363af4")]
            public virtual RepoItemInfo Text1003Info
            {
                get
                {
                    return _text1003Info;
                }
            }

            /// <summary>
            /// The Button1001 item.
            /// </summary>
            [RepositoryItem("b12677d5-b8a9-4215-ae03-df6b12504578")]
            public virtual Ranorex.Button Button1001
            {
                get
                {
                    return _button1001Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1001 item info.
            /// </summary>
            [RepositoryItemInfo("b12677d5-b8a9-4215-ae03-df6b12504578")]
            public virtual RepoItemInfo Button1001Info
            {
                get
                {
                    return _button1001Info;
                }
            }

            /// <summary>
            /// The Button1009 item.
            /// </summary>
            [RepositoryItem("ac3382a7-5d80-46dd-ac14-c2a2616a5535")]
            public virtual Ranorex.Button Button1009
            {
                get
                {
                    return _button1009Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1009 item info.
            /// </summary>
            [RepositoryItemInfo("ac3382a7-5d80-46dd-ac14-c2a2616a5535")]
            public virtual RepoItemInfo Button1009Info
            {
                get
                {
                    return _button1009Info;
                }
            }

            /// <summary>
            /// The Button1008 item.
            /// </summary>
            [RepositoryItem("a712cb93-0819-4d4d-b36c-c6e66090fe08")]
            public virtual Ranorex.Button Button1008
            {
                get
                {
                    return _button1008Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1008 item info.
            /// </summary>
            [RepositoryItemInfo("a712cb93-0819-4d4d-b36c-c6e66090fe08")]
            public virtual RepoItemInfo Button1008Info
            {
                get
                {
                    return _button1008Info;
                }
            }

            /// <summary>
            /// The Text1014 item.
            /// </summary>
            [RepositoryItem("38df9221-e1a6-41e0-be29-4d2a2984470a")]
            public virtual Ranorex.Text Text1014
            {
                get
                {
                    return _text1014Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1014 item info.
            /// </summary>
            [RepositoryItemInfo("38df9221-e1a6-41e0-be29-4d2a2984470a")]
            public virtual RepoItemInfo Text1014Info
            {
                get
                {
                    return _text1014Info;
                }
            }

            /// <summary>
            /// The Button1015 item.
            /// </summary>
            [RepositoryItem("873e1bcd-5d79-462d-9a30-e5680d423b1b")]
            public virtual Ranorex.Button Button1015
            {
                get
                {
                    return _button1015Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1015 item info.
            /// </summary>
            [RepositoryItemInfo("873e1bcd-5d79-462d-9a30-e5680d423b1b")]
            public virtual RepoItemInfo Button1015Info
            {
                get
                {
                    return _button1015Info;
                }
            }

            /// <summary>
            /// The CheckBox1013 item.
            /// </summary>
            [RepositoryItem("81650e56-03b2-447d-8514-e0a9db6d9fa5")]
            public virtual Ranorex.CheckBox CheckBox1013
            {
                get
                {
                    return _checkbox1013Info.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The CheckBox1013 item info.
            /// </summary>
            [RepositoryItemInfo("81650e56-03b2-447d-8514-e0a9db6d9fa5")]
            public virtual RepoItemInfo CheckBox1013Info
            {
                get
                {
                    return _checkbox1013Info;
                }
            }

            /// <summary>
            /// The Isconfig folder.
            /// </summary>
            [RepositoryFolder("5048c57e-70fe-417b-ac46-902a18dc604b")]
            public virtual setupMyrian_complexFlowRepositoryFolders.IsconfigFolder Isconfig
            {
                get { return _isconfig; }
            }
        }

        /// <summary>
        /// The IsconfigFolder folder.
        /// </summary>
        [RepositoryFolder("5048c57e-70fe-417b-ac46-902a18dc604b")]
        public partial class IsconfigFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text10061Info;
            RepoItemInfo _text10051Info;
            RepoItemInfo _text10071Info;
            RepoItemInfo _text10041Info;

            /// <summary>
            /// Creates a new Isconfig  folder.
            /// </summary>
            public IsconfigFolder(RepoGenBaseFolder parentFolder) :
                    base("Isconfig", "container[@instance='0']", parentFolder, 30000, null, false, "5048c57e-70fe-417b-ac46-902a18dc604b", "")
            {
                _text10061Info = new RepoItemInfo(this, "Text10061", "text[10]", 30000, null, "1215cd35-6a94-4c82-a3fd-806c0e2bab7a");
                _text10051Info = new RepoItemInfo(this, "Text10051", "text[4]", 30000, null, "1aa202bc-fdea-4163-aeb4-9e463c28b2db");
                _text10071Info = new RepoItemInfo(this, "Text10071", "text[8]", 30000, null, "2238a253-bba0-411b-8732-8a7ef6b8ab9c");
                _text10041Info = new RepoItemInfo(this, "Text10041", "text[@controlid='1004']", 30000, null, "dab9735f-d1d0-45e0-83c2-10b032b8fda8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5048c57e-70fe-417b-ac46-902a18dc604b")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5048c57e-70fe-417b-ac46-902a18dc604b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text10061 item.
            /// </summary>
            [RepositoryItem("1215cd35-6a94-4c82-a3fd-806c0e2bab7a")]
            public virtual Ranorex.Text Text10061
            {
                get
                {
                    return _text10061Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text10061 item info.
            /// </summary>
            [RepositoryItemInfo("1215cd35-6a94-4c82-a3fd-806c0e2bab7a")]
            public virtual RepoItemInfo Text10061Info
            {
                get
                {
                    return _text10061Info;
                }
            }

            /// <summary>
            /// The Text10051 item.
            /// </summary>
            [RepositoryItem("1aa202bc-fdea-4163-aeb4-9e463c28b2db")]
            public virtual Ranorex.Text Text10051
            {
                get
                {
                    return _text10051Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text10051 item info.
            /// </summary>
            [RepositoryItemInfo("1aa202bc-fdea-4163-aeb4-9e463c28b2db")]
            public virtual RepoItemInfo Text10051Info
            {
                get
                {
                    return _text10051Info;
                }
            }

            /// <summary>
            /// The Text10071 item.
            /// </summary>
            [RepositoryItem("2238a253-bba0-411b-8732-8a7ef6b8ab9c")]
            public virtual Ranorex.Text Text10071
            {
                get
                {
                    return _text10071Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text10071 item info.
            /// </summary>
            [RepositoryItemInfo("2238a253-bba0-411b-8732-8a7ef6b8ab9c")]
            public virtual RepoItemInfo Text10071Info
            {
                get
                {
                    return _text10071Info;
                }
            }

            /// <summary>
            /// The Text10041 item.
            /// </summary>
            [RepositoryItem("dab9735f-d1d0-45e0-83c2-10b032b8fda8")]
            public virtual Ranorex.Text Text10041
            {
                get
                {
                    return _text10041Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text10041 item info.
            /// </summary>
            [RepositoryItemInfo("dab9735f-d1d0-45e0-83c2-10b032b8fda8")]
            public virtual RepoItemInfo Text10041Info
            {
                get
                {
                    return _text10041Info;
                }
            }
        }

        /// <summary>
        /// The MyrianRConfigurationAppFolder folder.
        /// </summary>
        [RepositoryFolder("e2c8eff0-b367-4055-9105-3fa08a94f2f9")]
        public partial class MyrianRConfigurationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _button6Info;
            RepoItemInfo _button7Info;

            /// <summary>
            /// Creates a new MyrianRConfiguration  folder.
            /// </summary>
            public MyrianRConfigurationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MyrianRConfiguration", "/form[@title='Myrian® Configuration']", parentFolder, 30000, null, false, "e2c8eff0-b367-4055-9105-3fa08a94f2f9", "")
            {
                _button6Info = new RepoItemInfo(this, "Button6", "button[@controlid='6']", 30000, null, "7cf2eddc-2e11-4cc9-a7bb-40f9a8a96770");
                _button7Info = new RepoItemInfo(this, "Button7", "button[@controlid='7']", 30000, null, "684f294d-c79f-460a-af7f-6b0ebecb35f2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e2c8eff0-b367-4055-9105-3fa08a94f2f9")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e2c8eff0-b367-4055-9105-3fa08a94f2f9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Button6 item.
            /// </summary>
            [RepositoryItem("7cf2eddc-2e11-4cc9-a7bb-40f9a8a96770")]
            public virtual Ranorex.Button Button6
            {
                get
                {
                    return _button6Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button6 item info.
            /// </summary>
            [RepositoryItemInfo("7cf2eddc-2e11-4cc9-a7bb-40f9a8a96770")]
            public virtual RepoItemInfo Button6Info
            {
                get
                {
                    return _button6Info;
                }
            }

            /// <summary>
            /// The Button7 item.
            /// </summary>
            [RepositoryItem("684f294d-c79f-460a-af7f-6b0ebecb35f2")]
            public virtual Ranorex.Button Button7
            {
                get
                {
                    return _button7Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button7 item info.
            /// </summary>
            [RepositoryItemInfo("684f294d-c79f-460a-af7f-6b0ebecb35f2")]
            public virtual RepoItemInfo Button7Info
            {
                get
                {
                    return _button7Info;
                }
            }
        }

        /// <summary>
        /// The MyrianR200OuvertureDeSessionAppFolder folder.
        /// </summary>
        [RepositoryFolder("d02722bc-8a53-4579-ad5d-9e5d9fda9320")]
        public partial class MyrianR200OuvertureDeSessionAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _combobox880Info;
            RepoItemInfo _text882Info;
            RepoItemInfo _button1Info;
            RepoItemInfo _button2Info;

            /// <summary>
            /// Creates a new MyrianR200OuvertureDeSession  folder.
            /// </summary>
            public MyrianR200OuvertureDeSessionAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MyrianR200OuvertureDeSession", "/form[@title~'^Myrian®\\ 2\\.0\\.0\\ -\\ Ouverture']", parentFolder, 30000, null, false, "d02722bc-8a53-4579-ad5d-9e5d9fda9320", "")
            {
                _combobox880Info = new RepoItemInfo(this, "ComboBox880", "combobox[@controlid='880']", 30000, null, "4670a8c8-802b-45a8-85a7-e5ba44d895c3");
                _text882Info = new RepoItemInfo(this, "Text882", "text[@controlid='882']", 30000, null, "5a67676c-f04d-409e-98b9-42ff0ae10510");
                _button1Info = new RepoItemInfo(this, "Button1", "button[@controlid='1']", 30000, null, "f3759d92-048c-44a0-93d3-8500b85f2e35");
                _button2Info = new RepoItemInfo(this, "Button2", "button[@controlid='2']", 30000, null, "c1e35d62-ed11-4094-8817-d84d1842b4d3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d02722bc-8a53-4579-ad5d-9e5d9fda9320")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d02722bc-8a53-4579-ad5d-9e5d9fda9320")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ComboBox880 item.
            /// </summary>
            [RepositoryItem("4670a8c8-802b-45a8-85a7-e5ba44d895c3")]
            public virtual Ranorex.ComboBox ComboBox880
            {
                get
                {
                    return _combobox880Info.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ComboBox880 item info.
            /// </summary>
            [RepositoryItemInfo("4670a8c8-802b-45a8-85a7-e5ba44d895c3")]
            public virtual RepoItemInfo ComboBox880Info
            {
                get
                {
                    return _combobox880Info;
                }
            }

            /// <summary>
            /// The Text882 item.
            /// </summary>
            [RepositoryItem("5a67676c-f04d-409e-98b9-42ff0ae10510")]
            public virtual Ranorex.Text Text882
            {
                get
                {
                    return _text882Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text882 item info.
            /// </summary>
            [RepositoryItemInfo("5a67676c-f04d-409e-98b9-42ff0ae10510")]
            public virtual RepoItemInfo Text882Info
            {
                get
                {
                    return _text882Info;
                }
            }

            /// <summary>
            /// The Button1 item.
            /// </summary>
            [RepositoryItem("f3759d92-048c-44a0-93d3-8500b85f2e35")]
            public virtual Ranorex.Button Button1
            {
                get
                {
                    return _button1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1 item info.
            /// </summary>
            [RepositoryItemInfo("f3759d92-048c-44a0-93d3-8500b85f2e35")]
            public virtual RepoItemInfo Button1Info
            {
                get
                {
                    return _button1Info;
                }
            }

            /// <summary>
            /// The Button2 item.
            /// </summary>
            [RepositoryItem("c1e35d62-ed11-4094-8817-d84d1842b4d3")]
            public virtual Ranorex.Button Button2
            {
                get
                {
                    return _button2Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button2 item info.
            /// </summary>
            [RepositoryItemInfo("c1e35d62-ed11-4094-8817-d84d1842b4d3")]
            public virtual RepoItemInfo Button2Info
            {
                get
                {
                    return _button2Info;
                }
            }
        }

        /// <summary>
        /// The MyrianRAppFolder folder.
        /// </summary>
        [RepositoryFolder("50db8392-3d5e-44a1-beaa-bdd1eff0d31f")]
        public partial class MyrianRAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _button2Info;

            /// <summary>
            /// Creates a new MyrianR  folder.
            /// </summary>
            public MyrianRAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MyrianR", "/form[@title='Myrian®']", parentFolder, 30000, null, false, "50db8392-3d5e-44a1-beaa-bdd1eff0d31f", "")
            {
                _button2Info = new RepoItemInfo(this, "Button2", "button[@controlid='2']", 30000, null, "24282759-4d91-4ef0-a2d4-7baafcda93ec");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("50db8392-3d5e-44a1-beaa-bdd1eff0d31f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("50db8392-3d5e-44a1-beaa-bdd1eff0d31f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Button2 item.
            /// </summary>
            [RepositoryItem("24282759-4d91-4ef0-a2d4-7baafcda93ec")]
            public virtual Ranorex.Button Button2
            {
                get
                {
                    return _button2Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button2 item info.
            /// </summary>
            [RepositoryItemInfo("24282759-4d91-4ef0-a2d4-7baafcda93ec")]
            public virtual RepoItemInfo Button2Info
            {
                get
                {
                    return _button2Info;
                }
            }
        }

        /// <summary>
        /// The MyrianRCalibrationEcranC2005IntraAppFolder folder.
        /// </summary>
        [RepositoryFolder("be9bb14f-4633-4a2c-9a16-71cc5cfbd142")]
        public partial class MyrianRCalibrationEcranC2005IntraAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _button2Info;

            /// <summary>
            /// Creates a new MyrianRCalibrationEcranC2005Intra  folder.
            /// </summary>
            public MyrianRCalibrationEcranC2005IntraAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MyrianRCalibrationEcranC2005Intra", "/form[@title~'^Myrian®\\ Calibration\\ Ecran']", parentFolder, 30000, null, false, "be9bb14f-4633-4a2c-9a16-71cc5cfbd142", "")
            {
                _button2Info = new RepoItemInfo(this, "Button2", "button[@controlid='2']", 30000, null, "f62770e5-07fc-45d8-bbc4-3ac5be0e2616");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("be9bb14f-4633-4a2c-9a16-71cc5cfbd142")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("be9bb14f-4633-4a2c-9a16-71cc5cfbd142")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Button2 item.
            /// </summary>
            [RepositoryItem("f62770e5-07fc-45d8-bbc4-3ac5be0e2616")]
            public virtual Ranorex.Button Button2
            {
                get
                {
                    return _button2Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button2 item info.
            /// </summary>
            [RepositoryItemInfo("f62770e5-07fc-45d8-bbc4-3ac5be0e2616")]
            public virtual RepoItemInfo Button2Info
            {
                get
                {
                    return _button2Info;
                }
            }
        }

        /// <summary>
        /// The ContratDeLicenceEULAAppFolder folder.
        /// </summary>
        [RepositoryFolder("373ba717-f1fb-482f-a330-a49817b14f28")]
        public partial class ContratDeLicenceEULAAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _checkbox2134Info;
            RepoItemInfo _button1Info;

            /// <summary>
            /// Creates a new ContratDeLicenceEULA  folder.
            /// </summary>
            public ContratDeLicenceEULAAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ContratDeLicenceEULA", "/form[@title='Contrat de Licence (EULA)']", parentFolder, 30000, null, false, "373ba717-f1fb-482f-a330-a49817b14f28", "")
            {
                _checkbox2134Info = new RepoItemInfo(this, "CheckBox2134", "checkbox[@controlid='2134']", 30000, null, "8dc66632-1327-461e-af85-81582ecd57b9");
                _button1Info = new RepoItemInfo(this, "Button1", "button[@controlid='1']", 30000, null, "ebcae159-32c1-4072-bf04-6e977ac759b2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("373ba717-f1fb-482f-a330-a49817b14f28")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("373ba717-f1fb-482f-a330-a49817b14f28")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CheckBox2134 item.
            /// </summary>
            [RepositoryItem("8dc66632-1327-461e-af85-81582ecd57b9")]
            public virtual Ranorex.CheckBox CheckBox2134
            {
                get
                {
                    return _checkbox2134Info.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The CheckBox2134 item info.
            /// </summary>
            [RepositoryItemInfo("8dc66632-1327-461e-af85-81582ecd57b9")]
            public virtual RepoItemInfo CheckBox2134Info
            {
                get
                {
                    return _checkbox2134Info;
                }
            }

            /// <summary>
            /// The Button1 item.
            /// </summary>
            [RepositoryItem("ebcae159-32c1-4072-bf04-6e977ac759b2")]
            public virtual Ranorex.Button Button1
            {
                get
                {
                    return _button1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1 item info.
            /// </summary>
            [RepositoryItemInfo("ebcae159-32c1-4072-bf04-6e977ac759b2")]
            public virtual RepoItemInfo Button1Info
            {
                get
                {
                    return _button1Info;
                }
            }
        }

        /// <summary>
        /// The MyrianR200AppFolder folder.
        /// </summary>
        [RepositoryFolder("9ba5d511-ddeb-48c4-adb2-c8dfffa3478e")]
        public partial class MyrianR200AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _afxwnd140Info;
            RepoItemInfo _button1052Info;
            RepoItemInfo _button737Info;

            /// <summary>
            /// Creates a new MyrianR200  folder.
            /// </summary>
            public MyrianR200AppFolder(RepoGenBaseFolder parentFolder) :
                    base("MyrianR200", "/form[@title='Myrian® 2.0.0']", parentFolder, 30000, null, false, "9ba5d511-ddeb-48c4-adb2-c8dfffa3478e", "")
            {
                _afxwnd140Info = new RepoItemInfo(this, "AfxWnd140", "element[@instance='0']", 30000, null, "be6607ba-199b-4f60-8ce6-8a42bfa5debf");
                _button1052Info = new RepoItemInfo(this, "Button1052", "container[@instance='1']/container[@instance='0']/button[@controlid='1052']", 30000, null, "712faec6-0618-491e-b402-b443f523054a");
                _button737Info = new RepoItemInfo(this, "Button737", "?/?/button[@controlid='737']", 30000, null, "c6f96bbf-ae60-4fda-843f-e22f4e8ab9f9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9ba5d511-ddeb-48c4-adb2-c8dfffa3478e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9ba5d511-ddeb-48c4-adb2-c8dfffa3478e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AfxWnd140 item.
            /// </summary>
            [RepositoryItem("be6607ba-199b-4f60-8ce6-8a42bfa5debf")]
            public virtual Ranorex.Unknown AfxWnd140
            {
                get
                {
                    return _afxwnd140Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The AfxWnd140 item info.
            /// </summary>
            [RepositoryItemInfo("be6607ba-199b-4f60-8ce6-8a42bfa5debf")]
            public virtual RepoItemInfo AfxWnd140Info
            {
                get
                {
                    return _afxwnd140Info;
                }
            }

            /// <summary>
            /// The Button1052 item.
            /// </summary>
            [RepositoryItem("712faec6-0618-491e-b402-b443f523054a")]
            public virtual Ranorex.Button Button1052
            {
                get
                {
                    return _button1052Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1052 item info.
            /// </summary>
            [RepositoryItemInfo("712faec6-0618-491e-b402-b443f523054a")]
            public virtual RepoItemInfo Button1052Info
            {
                get
                {
                    return _button1052Info;
                }
            }

            /// <summary>
            /// The Button737 item.
            /// </summary>
            [RepositoryItem("c6f96bbf-ae60-4fda-843f-e22f4e8ab9f9")]
            public virtual Ranorex.Button Button737
            {
                get
                {
                    return _button737Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button737 item info.
            /// </summary>
            [RepositoryItemInfo("c6f96bbf-ae60-4fda-843f-e22f4e8ab9f9")]
            public virtual RepoItemInfo Button737Info
            {
                get
                {
                    return _button737Info;
                }
            }
        }

    }
#pragma warning restore 0436
}